package scoutapp.com.br.scoutapp.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ATHLETE".
 */
public class Athlete implements java.io.Serializable {

    private Long id;
    private String name;
    private Integer age;
    private String category;
    private String club;
    private Integer hand;
    private Integer style;
    private String obs;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Athlete() {
    }

    public Athlete(Long id) {
        this.id = id;
    }

    public Athlete(Long id, String name, Integer age, String category, String club, Integer hand, Integer style, String obs) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.category = category;
        this.club = club;
        this.hand = hand;
        this.style = style;
        this.obs = obs;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getClub() {
        return club;
    }

    public void setClub(String club) {
        this.club = club;
    }

    public Integer getHand() {
        return hand;
    }

    public void setHand(Integer hand) {
        this.hand = hand;
    }

    public Integer getStyle() {
        return style;
    }

    public void setStyle(Integer style) {
        this.style = style;
    }

    public String getObs() {
        return obs;
    }

    public void setObs(String obs) {
        this.obs = obs;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
