package scoutapp.com.br.scoutapp.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CHAMPIONSHIP".
 */
public class Championship implements java.io.Serializable {

    private Long id;
    private String champName;
    private java.util.Date date;
    private String state;
    private String city;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Championship() {
    }

    public Championship(Long id) {
        this.id = id;
    }

    public Championship(Long id, String champName, java.util.Date date, String state, String city) {
        this.id = id;
        this.champName = champName;
        this.date = date;
        this.state = state;
        this.city = city;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getChampName() {
        return champName;
    }

    public void setChampName(String champName) {
        this.champName = champName;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
