package scoutapp.com.br.scoutapp.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import scoutapp.com.br.scoutapp.model.Athlete;
import scoutapp.com.br.scoutapp.model.Championship;
import scoutapp.com.br.scoutapp.model.User;
import scoutapp.com.br.scoutapp.model.GameUser;
import scoutapp.com.br.scoutapp.model.GameOpponent;

import scoutapp.com.br.scoutapp.model.AthleteDao;
import scoutapp.com.br.scoutapp.model.ChampionshipDao;
import scoutapp.com.br.scoutapp.model.UserDao;
import scoutapp.com.br.scoutapp.model.GameUserDao;
import scoutapp.com.br.scoutapp.model.GameOpponentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig athleteDaoConfig;
    private final DaoConfig championshipDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig gameUserDaoConfig;
    private final DaoConfig gameOpponentDaoConfig;

    private final AthleteDao athleteDao;
    private final ChampionshipDao championshipDao;
    private final UserDao userDao;
    private final GameUserDao gameUserDao;
    private final GameOpponentDao gameOpponentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        athleteDaoConfig = daoConfigMap.get(AthleteDao.class).clone();
        athleteDaoConfig.initIdentityScope(type);

        championshipDaoConfig = daoConfigMap.get(ChampionshipDao.class).clone();
        championshipDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        gameUserDaoConfig = daoConfigMap.get(GameUserDao.class).clone();
        gameUserDaoConfig.initIdentityScope(type);

        gameOpponentDaoConfig = daoConfigMap.get(GameOpponentDao.class).clone();
        gameOpponentDaoConfig.initIdentityScope(type);

        athleteDao = new AthleteDao(athleteDaoConfig, this);
        championshipDao = new ChampionshipDao(championshipDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        gameUserDao = new GameUserDao(gameUserDaoConfig, this);
        gameOpponentDao = new GameOpponentDao(gameOpponentDaoConfig, this);

        registerDao(Athlete.class, athleteDao);
        registerDao(Championship.class, championshipDao);
        registerDao(User.class, userDao);
        registerDao(GameUser.class, gameUserDao);
        registerDao(GameOpponent.class, gameOpponentDao);
    }
    
    public void clear() {
        athleteDaoConfig.getIdentityScope().clear();
        championshipDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        gameUserDaoConfig.getIdentityScope().clear();
        gameOpponentDaoConfig.getIdentityScope().clear();
    }

    public AthleteDao getAthleteDao() {
        return athleteDao;
    }

    public ChampionshipDao getChampionshipDao() {
        return championshipDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public GameUserDao getGameUserDao() {
        return gameUserDao;
    }

    public GameOpponentDao getGameOpponentDao() {
        return gameOpponentDao;
    }

}
